#!/bin/bash

# Copyright (c) 2020-2021, Windscribe Limited. All rights reserved.
# Usage: dns-leak-protect up|down [interface_name]


cmd() {
	echo "[#] $*" >&2
	"$@"
}

dnsleak_protection_up() 
{

	local interface_name="$1"
	shift
	local marker="-m comment --comment \"Windscribe client dns leak protection\""

	if [ -z "$interface_name" ]
	then
   		echo "\$interface_name is empty"
   		return 0
	fi

	local rules=$'*filter\n'
	printf -v rules '%s:windscribe_dnsleaks - [0:0]\n' "$rules"
	printf -v rules '%s-I OUTPUT 1 -j windscribe_dnsleaks %s\n' "$rules" "$marker"
	printf -v rules '%s-A windscribe_dnsleaks -o lo -j ACCEPT %s\n' "$rules" "$marker"
	# allow DNS servers that we've configured
	for i in $@; do
		printf -v rules '%s-A windscribe_dnsleaks -o %s -d %s -j ACCEPT %s\n' "$rules" "$interface_name" "$i" "$marker"
	done
	# disallow all others
	printf -v rules '%s-A windscribe_dnsleaks -p udp --dport 53 -j DROP %s\n' "$rules" "$marker"
	printf -v rules '%s-A windscribe_dnsleaks -p tcp --dport 53 -j DROP %s\n' "$rules" "$marker"

	printf -v rules '%sCOMMIT\n' "$rules"

	echo -n "$rules" | cmd "/sbin/iptables-restore" -n
}


dnsleak_protection_down() 
{

	local line iptables found restore in_filter_section
	restore="" found=0 is_filter_section=0
	while read -r line; do
		if [[ $line == "*filter"* ]]; then
			is_filter_section=1
		else
			[[ $line == "*"* ]] && is_filter_section=0
		fi

		[[ $line == "*"* || $line == COMMIT || $line == "-A "*"-m comment --comment \"Windscribe client dns leak protection\""* ]] || continue
		[[ $line == "-A"* ]] && found=1
		
		if [[ $is_filter_section -ne 0 && $line == COMMIT ]]; then
			printf -v restore '%s-X windscribe_dnsleaks\n' "$restore"
		fi
		printf -v restore '%s%s\n' "$restore" "${line/#-A/-D}"

	done < <(/sbin/iptables-save 2>/dev/null)
	
	if [[ $found -ne 0 ]]; then
		echo -n "$restore" | cmd "/sbin/iptables-restore" -n
	fi
}


main() {
	local action="$1"
	shift

	if [[ $action == "up" ]]; then
		dnsleak_protection_up $@
	elif [[ $action == "down" ]]; then
		dnsleak_protection_down
	else
		echo "Usage: dns-leak-protect up|down [interface_name] [servers_to_allow]"
		return 1
	fi
}


main "$@"
