#!/bin/bash

mode=$1

if [ "$mode" == "up" ]; then
    mark=$2
    def_gateway=$3
    def_interface=$4
    vpn_gateway=$5
    vpn_interface=$6
    remote_ip=$7

    mkdir -p /etc/iproute2 # create dir if it doesn't exist
    touch /etc/iproute2/rt_tables # create file if it doesn't exist

    # Add "windscribe" table definition if it doesn't exist
    if [ "`grep -c "69 windscribe" /etc/iproute2/rt_tables`" -eq 0 ]; then
        echo "69 windscribe" >> /etc/iproute2/rt_tables
    fi
    if [ "`grep -c "70 windscribe_include" /etc/iproute2/rt_tables`" -eq 0 ]; then
        echo "70 windscribe_include" >> /etc/iproute2/rt_tables
    fi

    # Create separate routing table for packets with our mark
    ip route add default via $def_gateway dev $def_interface table windscribe
    ip route add 10.255.255.0/24 dev $vpn_interface table windscribe

    # Create separate routing table for packets that should always go into tunnel
    ip rule add fwmark $mark priority 16384 table windscribe
    ip route add default via $vpn_gateway dev $vpn_interface table windscribe_include
    ip route add $remote_ip dev $def_interface table windscribe_include

elif [ "$mode" == "down" ]; then
    ip rule flush table windscribe 2>/dev/null
    ip route flush table windscribe 2>/dev/null
    ip rule flush table windscribe_include 2>/dev/null
    ip route flush table windscribe_include 2>/dev/null
fi

exit 0
