#!/bin/bash
# 
# Parses DHCP options from openvpn to update DNS by writing directly to /etc/resolv.conf
# Example envs set from openvpn:
#
#     foreign_option_1='dhcp-option DNS 193.43.27.132'
#     foreign_option_2='dhcp-option DNS 193.43.27.133'
#     foreign_option_3='dhcp-option DOMAIN be.bnc.ch'
#

[ "$script_type" ] || exit 0
[ "$dev" ] || exit 0


SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
DNS_LEAK_SCRIPT=$SCRIPT_DIR/dns-leak-protect

case "$script_type" in
  up)
    if [ ! -d /tmp/windscribe_openvpn ]; then
        mkdir /tmp/windscribe_openvpn
    fi
    CACHE_NAMESERVER="/tmp/windscribe_openvpn/$DEV.nameserver"
    echo -n "" > $CACHE_NAMESERVER

    dns=dns
    for opt in ${!foreign_option_*}
    do
        eval "dns=\${$opt#dhcp-option DNS }"
        if [[ $dns =~ [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]]; then
            if [ ! -f /etc/resolv.conf.default ]; then
                cp /etc/resolv.conf /etc/resolv.conf.default
            fi

            cat /etc/resolv.conf | grep -v ^# | grep -v ^nameserver > /tmp/resolv.conf
            echo "nameserver $dns" >> /tmp/resolv.conf
            echo $dns >> $CACHE_NAMESERVER
            cat /etc/resolv.conf | grep -v ^# | grep -v "nameserver $dns" | grep nameserver >> /tmp/resolv.conf
            mv /tmp/resolv.conf /etc/resolv.conf

        fi
    done

    "$DNS_LEAK_SCRIPT" "up" ${dev}
	;;
  down)

    CACHE_NAMESERVER="/tmp/windscribe_openvpn/$DEV.nameserver"
    echo $CACHE_NAMESERVER

    if [ -f $CACHE_NAMESERVER ]; then
        for ns in `cat $CACHE_NAMESERVER`; do
            echo "Removing $ns from /etc/resolv.conf"
            cat /etc/resolv.conf | grep -v "nameserver $ns" > /tmp/resolv.conf
            mv /tmp/resolv.conf /etc/resolv.conf

        done
    fi

	"$DNS_LEAK_SCRIPT" "down"
	;;
esac


