#ifndef EXECUTABLE_SIGNATURE_DEFS_H
#define EXECUTABLE_SIGNATURE_DEFS_H

#define WINDOWS_CERT_SUBJECT_NAME L"Windscribe Limited"
#define MACOS_CERT_DEVELOPER_ID "Developer ID Application: Windscribe Limited (GYZJYS7XUG)"

#endif // EXECUTABLE_SIGNATURE_DEFS_H
