/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: apiinfo.proto */

#ifndef PROTOBUF_C_apiinfo_2eproto__INCLUDED
#define PROTOBUF_C_apiinfo_2eproto__INCLUDED

#include "protobuf-c/protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

typedef struct ProtoApiInfo__WireGuardConfig ProtoApiInfo__WireGuardConfig;


/* --- enums --- */


/* --- messages --- */

struct  ProtoApiInfo__WireGuardConfig
{
  ProtobufCMessage base;
  char *public_key;
  char *private_key;
  char *preshared_key;
  char *allowed_ips;
};
#define PROTO_API_INFO__WIRE_GUARD_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&proto_api_info__wire_guard_config__descriptor) \
    , NULL, NULL, NULL, NULL }


/* ProtoApiInfo__WireGuardConfig methods */
void   proto_api_info__wire_guard_config__init
                     (ProtoApiInfo__WireGuardConfig         *message);
size_t proto_api_info__wire_guard_config__get_packed_size
                     (const ProtoApiInfo__WireGuardConfig   *message);
size_t proto_api_info__wire_guard_config__pack
                     (const ProtoApiInfo__WireGuardConfig   *message,
                      uint8_t             *out);
size_t proto_api_info__wire_guard_config__pack_to_buffer
                     (const ProtoApiInfo__WireGuardConfig   *message,
                      ProtobufCBuffer     *buffer);
ProtoApiInfo__WireGuardConfig *
       proto_api_info__wire_guard_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   proto_api_info__wire_guard_config__free_unpacked
                     (ProtoApiInfo__WireGuardConfig *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ProtoApiInfo__WireGuardConfig_Closure)
                 (const ProtoApiInfo__WireGuardConfig *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor proto_api_info__wire_guard_config__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_apiinfo_2eproto__INCLUDED */
