#ifndef LOCATIONSTRAYMENUTYPES_H
#define LOCATIONSTRAYMENUTYPES_H

enum LocationsTrayMenuType
{
    LOCATIONS_TRAY_MENU_TYPE_GENERIC,
    LOCATIONS_TRAY_MENU_TYPE_FAVORITES,
    LOCATIONS_TRAY_MENU_TYPE_STATIC_IPS,
    LOCATIONS_TRAY_MENU_TYPE_CUSTOM_CONFIGS,
    LOCATIONS_TRAY_MENU_NUM_TYPES
};

#endif // LOCATIONSTRAYMENUTYPES_H
