#!/bin/bash
# This file overwrites the debian-specific postinst during fpm call in build script 
# So if multi-platform change is needed remember to change that file as well
set -e
systemctl preset windscribe-helper
systemctl start windscribe-helper
ln -s /opt/windscribe/windscribe-cli /usr/bin/windscribe-cli
update-desktop-database

echo linux_rpm_x64 > ../etc/windscribe/platform # platform-specific

