#!/bin/bash
# This file overwrites the debian-specific postinst during fpm call in build script 
# So if multi-platform change is needed remember to change that file as well
set -e
systemctl enable windscribe-helper
systemctl start windscribe-helper
echo linux_rpm_x64 > ../etc/windscribe/platform # platform-specific

