#!/bin/bash
#*******************************************************************************
# Windscribe Build System
# Copyright (c) 2020-2021, Windscribe Limited. All rights reserved.
#*******************************************************************************
# HOOK:    pre-commit
# PURPOSE: checks commited files with static code analyzer.
# AUTHOR:  Alexander Popov (alexander.popov@windscribe.com)
#*******************************************************************************

EMSG="\e[1;31mERROR:\e[0;39m"

pythonexename=$PYTHONHOME
if [ -n "$pythonexename" ]; then pythonexename=${pythonexename}/; fi
pythonexename=${pythonexename}python

type "$pythonexename" >/dev/null 2>&1 || \
 { printf "$EMSG Python is not installed, aborting.\n"; exit 1; }
type cppcheck >/dev/null 2>&1 || \
 { printf "$EMSG CppCheck is not installed, aborting.\n"; exit 1; }

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

files_for_cppcheck=$(git diff-index --cached $against | \
  grep -v 'common[\/\\]prepare_build_environment[\/\\]' | \
  grep -v 'common[\/\\]wintun[\/\\]' | \
  grep -v 'installer[\/\\]' | \
  grep -E '[MA]	.*\.(c|cpp|cc|cxx)$' | cut -d'	' -f 2)

if [ -n "$files_for_cppcheck" ]; then
  num_files=$(echo $files_for_cppcheck | tr -cd ' \t' | wc -c)
  if [ $num_files -gt 5 ]; then
    printf "Running cppcheck for $num_files files, please wait...\n"
  fi
  echo ${files_for_cppcheck[@]} | "$pythonexename" "tools/run_cppcheck.py" --pipe
  if [ $? -ne 0 ]; then exit 1; fi
fi
