#!/bin/bash
set -e

systemctl stop windscribe-helper || true
systemctl disable windscribe-helper || true
/opt/windscribe/helper --reset-mac-addresses

if [ $1 != "upgrade" ]; then
    killall -q Windscribe || true
    deluser windscribe || true
    delgroup windscribe || true

    rm -rf /var/log/windscribe
    rm -rf /etc/windscribe
    rm -f /usr/bin/windscribe-cli
fi
