#!/bin/bash
# This file will be overwritten by rpm specific script which is passed to fpm in build script
# So if multi-platform change is needed remember to change that file as well
systemctl enable windscribe-helper
systemctl start windscribe-helper
ln -sf /opt/windscribe/windscribe-cli /usr/bin/windscribe-cli
setcap cap_setgid+ep /opt/windscribe/Windscribe
update-desktop-database || true

# delete/migrate previous temporary files if any
rm -rf /etc/windscribe/stunnel.conf /etc/windscribe/config.ovpn /etc/windscribe/windscribe_servers

mkdir -p /etc/windscribe
if [ "`uname -m`" == "aarch64" ]; then
    echo linux_deb_arm64 > /etc/windscribe/platform
else
    echo linux_deb_x64 > /etc/windscribe/platform
fi

