import "oaidl.idl";
import "ocidl.idl";
import "unknwn.idl";

// GUIDs generated in windscribe_auth_helper project

// Interface IMyThing
[
	object, 
	uuid(C7160B73-174A-4559-89B5-F1E99BA45F1B), // IID_IAuthHelper
	helpstring("IAuthHelper Interface"),
	pointer_default(unique),
	dual,
	oleautomation,
	nonextensible
]
interface IAuthHelper : IUnknown
{
};

// MyLib
[
	uuid(22ED1313-72D9-48DF-828C-BAAB3DFF9A7E), // LIB_ID
	version(1.0),
	helpstring("AuthHelper Type Library"),
]
library MyLib
{
	importlib("stdole32.tlb");

	// Component CMyThing
	[
		uuid(B8E661E9-A6D5-463D-9EF3-0434D51AEA3B), // CLSID_CAuthHelper
		helpstring("CAuthHelper Class")
	]
	coclass CMyThing 
	{
		[default] interface IAuthHelper;
	};
};