#!/bin/bash

systemctl stop windscribe-helper || true
systemctl disable windscribe-helper || true
if [ -x /opt/windscribe/helper ]; then
    /opt/windscribe/helper --reset-mac-addresses || true
fi

if [ $1 != "upgrade" ]; then
    killall -q Windscribe || true
    deluser windscribe || true
    delgroup windscribe || true

    rm -rf /var/log/windscribe
    rm -rf /var/lib/windscribe
    rm -rf /etc/windscribe
    rm -f /usr/bin/windscribe-cli
fi
