#include <ntddk.h>
#include <wdf.h>
#pragma warning(disable : 4201)
#include <fwpsk.h>
#include "WindscribeCallout.h"
#include "CalloutFunctions.h"

WDFDEVICE wdfDevice = NULL;
// Variable for the run-time callout identifier
UINT32 NonTcpCalloutId = 0;
UINT32 TcpCalloutId = 0;
UINT32 NonTcpCalloutV6Id = 0;
UINT32 TcpCalloutV6Id = 0;

EVT_WDF_DRIVER_UNLOAD UnloadFunc;

// Also used to undo a partial registration in DriverEntry: the framework does not call
// EvtDriverUnload when DriverEntry fails, and a callout left registered would pin the driver -
// it could then be neither unloaded nor cleanly restarted.
static void UnregisterCallouts(void)
{
    static UINT32 *const calloutIds[] = { &NonTcpCalloutId, &TcpCalloutId, &NonTcpCalloutV6Id, &TcpCalloutV6Id };
    NTSTATUS status;
    ULONG i;

    for (i = 0; i < ARRAYSIZE(calloutIds); i++)
    {
        if (*calloutIds[i] == 0)
        {
            continue;
        }
        status = FwpsCalloutUnregisterById0(*calloutIds[i]);
        if (status != STATUS_SUCCESS)
        {
            // Not expected: unregistration succeeds even while filters still reference the callout,
            // and the documented failures cannot occur here - we never associate a flow context, and
            // both callers run once on a single thread, so no concurrent (un)registration is possible.
            KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_INFO_LEVEL, "WindscribeSplitTunnel: FwpsCalloutUnregisterById0 failed for callout %u, status 0x%X\n", *calloutIds[i], status));
            continue;
        }
        *calloutIds[i] = 0;
    }
}

static NTSTATUS FailDriverEntry(NTSTATUS status)
{
    UnregisterCallouts();
    return status;
}

NTSTATUS
DriverEntry(
    _In_ PDRIVER_OBJECT     DriverObject,
    _In_ PUNICODE_STRING    RegistryPath
)
{
    NTSTATUS status = STATUS_SUCCESS;
    WDF_DRIVER_CONFIG config;
    WDFDRIVER driver;
    PWDFDEVICE_INIT deviceInit;
    PDEVICE_OBJECT deviceObject = NULL;
    FWPS_CALLOUT1 nonTcpCallout = { 0 };
    FWPS_CALLOUT1 tcpCallout = { 0 };
    FWPS_CALLOUT1 nonTcpCalloutV6 = { 0 };
    FWPS_CALLOUT1 tcpCalloutV6 = { 0 };

    // Initialize the driver configuration object
    WDF_DRIVER_CONFIG_INIT(&config, WDF_NO_EVENT_CALLBACK);

    config.DriverInitFlags |= WdfDriverInitNonPnpDriver;
    config.EvtDriverUnload = UnloadFunc;

    // Create the driver object
    status = WdfDriverCreate(DriverObject, RegistryPath, WDF_NO_OBJECT_ATTRIBUTES, &config,    &driver);

    if (status != STATUS_SUCCESS)
    {
        KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_INFO_LEVEL, "WindscribeSplitTunnel: WdfDriverCreate failed\n"));
        return status;
    }

    // Allocate a device initialization structure
    deviceInit = WdfControlDeviceInitAllocate(driver, &SDDL_DEVOBJ_KERNEL_ONLY);
    if (deviceInit == NULL)
    {
        KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_INFO_LEVEL, "WindscribeSplitTunnel: WdfControlDeviceInitAllocate failed\n"));
        return STATUS_INSUFFICIENT_RESOURCES;
    }

    // Set the device characteristics
    WdfDeviceInitSetCharacteristics(deviceInit, FILE_DEVICE_SECURE_OPEN, FALSE);
    WdfDeviceInitSetDeviceType(deviceInit, FILE_DEVICE_NETWORK);
    WdfDeviceInitSetCharacteristics(deviceInit, FILE_AUTOGENERATED_DEVICE_NAME, TRUE);

    // Create a framework device object
    status = WdfDeviceCreate(&deviceInit, WDF_NO_OBJECT_ATTRIBUTES, &wdfDevice);

    // Check status
    if (status == STATUS_SUCCESS)
    {
        // Initialization of the framework device object is complete
        WdfControlFinishInitializing(wdfDevice);

        // Get the associated WDM device object
        deviceObject = WdfDeviceWdmGetDeviceObject(wdfDevice);
    }
    else
    {
        // WdfDeviceCreate only consumes deviceInit when it succeeds
        KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_INFO_LEVEL, "WindscribeSplitTunnel: WdfDeviceCreate failed\n"));
        WdfDeviceInitFree(deviceInit);
        return status;
    }

    nonTcpCallout.calloutKey = WINDSCRIBE_BIND_CALLOUT_GUID;
    nonTcpCallout.classifyFn = ClassifyFn;
    nonTcpCallout.notifyFn = NotifyFn;

    status = FwpsCalloutRegister1(deviceObject, &nonTcpCallout, &NonTcpCalloutId);
    if (status != STATUS_SUCCESS)
    {
        KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_INFO_LEVEL, "WindscribeSplitTunnel: FwpsCalloutRegister1 (bind) failed\n"));
        return FailDriverEntry(status);
    }

    tcpCallout.calloutKey = WINDSCRIBE_TCP_CALLOUT_GUID;
    tcpCallout.classifyFn = ClassifyFn;
    tcpCallout.notifyFn = NotifyFn;

    status = FwpsCalloutRegister1(deviceObject, &tcpCallout, &TcpCalloutId);
    if (status != STATUS_SUCCESS)
    {
        KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_INFO_LEVEL, "WindscribeSplitTunnel: FwpsCalloutRegister1 (TCP) failed\n"));
        return FailDriverEntry(status);
    }

    nonTcpCalloutV6.calloutKey = WINDSCRIBE_BIND_CALLOUT_V6_GUID;
    nonTcpCalloutV6.classifyFn = ClassifyFnV6;
    nonTcpCalloutV6.notifyFn = NotifyFn;

    status = FwpsCalloutRegister1(deviceObject, &nonTcpCalloutV6, &NonTcpCalloutV6Id);
    if (status != STATUS_SUCCESS)
    {
        KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_INFO_LEVEL, "WindscribeSplitTunnel: FwpsCalloutRegister1 (bind v6) failed\n"));
        return FailDriverEntry(status);
    }

    tcpCalloutV6.calloutKey = WINDSCRIBE_TCP_CALLOUT_V6_GUID;
    tcpCalloutV6.classifyFn = ClassifyFnV6;
    tcpCalloutV6.notifyFn = NotifyFn;

    status = FwpsCalloutRegister1(deviceObject, &tcpCalloutV6, &TcpCalloutV6Id);
    if (status != STATUS_SUCCESS)
    {
        KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_INFO_LEVEL, "WindscribeSplitTunnel: FwpsCalloutRegister1 (TCP v6) failed\n"));
        return FailDriverEntry(status);
    }

    KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_INFO_LEVEL, "WindscribeSplitTunnel: DriverEntry successfully\n"));
    return status;
}

VOID UnloadFunc(_In_ WDFDRIVER Driver)
{
    UNREFERENCED_PARAMETER(Driver);

    UnregisterCallouts();

    // Delete the framework device object
    if (wdfDevice)
    {
        WdfObjectDelete(wdfDevice);
    }

    KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_INFO_LEVEL, "WindscribeSplitTunnel: UnloadFunc finished successfully\n"));
}