#ifndef GUI_LOCATIONS_CLICKABLEANDTOOLTIPRECTS_H
#define GUI_LOCATIONS_CLICKABLEANDTOOLTIPRECTS_H

#include "iitemdelegate.h"

namespace gui {

enum { TOOLTIP_P2P_RECT = 0, CLICKABLE_FAVORITE_RECT};

} // namespace gui


#endif // GUI_LOCATIONS_CLICKABLEANDTOOLTIPRECTS_H
