#!/usr/bin/env bash
#-------------------------------------------------------------------------------
# Windscribe Build System
# Copyright (c) 2020-2022, Windscribe Limited. All rights reserved.
#-------------------------------------------------------------------------------
tools_dir=$(dirname "$0")

PYTHONDONTWRITEBYTECODE=1 exec python3 "$tools_dir/build_all.py" "$@"
