/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: apiinfo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "apiinfo.pb-c.h"

void   proto_api_info__wire_guard_config__init
                     (ProtoApiInfo__WireGuardConfig         *message)
{
  static const ProtoApiInfo__WireGuardConfig init_value = PROTO_API_INFO__WIRE_GUARD_CONFIG__INIT;
  *message = init_value;
}
size_t proto_api_info__wire_guard_config__get_packed_size
                     (const ProtoApiInfo__WireGuardConfig *message)
{
  assert(message->base.descriptor == &proto_api_info__wire_guard_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_api_info__wire_guard_config__pack
                     (const ProtoApiInfo__WireGuardConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_api_info__wire_guard_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_api_info__wire_guard_config__pack_to_buffer
                     (const ProtoApiInfo__WireGuardConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_api_info__wire_guard_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoApiInfo__WireGuardConfig *
       proto_api_info__wire_guard_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoApiInfo__WireGuardConfig *)
     protobuf_c_message_unpack (&proto_api_info__wire_guard_config__descriptor,
                                allocator, len, data);
}
void   proto_api_info__wire_guard_config__free_unpacked
                     (ProtoApiInfo__WireGuardConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto_api_info__wire_guard_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}

static const ProtobufCFieldDescriptor proto_api_info__wire_guard_config__field_descriptors[4] =
{
  {
    "public_key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtoApiInfo__WireGuardConfig, public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "private_key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtoApiInfo__WireGuardConfig, private_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "preshared_key",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtoApiInfo__WireGuardConfig, preshared_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "allowed_ips",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ProtoApiInfo__WireGuardConfig, allowed_ips),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_api_info__wire_guard_config__field_indices_by_name[] = {
  3,   /* field[3] = allowed_ips */
  2,   /* field[2] = preshared_key */
  1,   /* field[1] = private_key */
  0,   /* field[0] = public_key */
};
static const ProtobufCIntRange proto_api_info__wire_guard_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor proto_api_info__wire_guard_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProtoApiInfo.WireGuardConfig",
  "WireGuardConfig",
  "ProtoApiInfo__WireGuardConfig",
  "ProtoApiInfo",
  sizeof(ProtoApiInfo__WireGuardConfig),
  4,
  proto_api_info__wire_guard_config__field_descriptors,
  proto_api_info__wire_guard_config__field_indices_by_name,
  1,  proto_api_info__wire_guard_config__number_ranges,
  (ProtobufCMessageInit) proto_api_info__wire_guard_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
